apiVersion: v1
kind: Service
metadata:
  name: flask-aws-monitor-service
spec:
  selector:
    app: flask-aws-monitor
  ports:
  - protocol: TCP
    port: 80             # Port for the external service
    targetPort: 5001     # Port your container listens on
  type: LoadBalancer     # Exposes externally (for remote k8s cluster)
